// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;

namespace Azure.ResourceManager.ApiManagement
{
    [CodeGenSuppress("GetAsync", typeof(bool?))]
    [CodeGenSuppress("Get", typeof(bool?))]
    public abstract partial class IssueContractResource : ArmResource
    {
        /// <summary> The default implementation for operation Get. </summary>
        /// <param name="expandCommentsAttachments"> Expand the comment attachments. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        [ForwardsClientCalls]
        public async Task<Response<IssueContractResource>> GetAsync(CancellationToken cancellationToken = default)
        {
            return await GetCoreAsync(expandCommentsAttachments, cancellationToken).ConfigureAwait(false);
        }

        /// <summary> The default implementation for operation Get. </summary>
        /// <param name="expandCommentsAttachments"> Expand the comment attachments. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        [ForwardsClientCalls]
        public Response<IssueContractResource> Get(CancellationToken cancellationToken = default)
        {
            return GetCore(expandCommentsAttachments, cancellationToken);
        }
    }
}
